artifacts_root: artifacts

data_transformation:
      train_data_path: artifacts/data_correction_1/train_data.pkl
      val_data_path: artifacts/data_correction_1/val_data.pkl

      # P
      root_dir: artifacts/data_transformation/${P}
      preprocessor_path: artifacts/data_transformation/${P}/preprocessor.pkl
      classes_path: artifacts/data_transformation/${P}/classes.pkl
      train_features_path: artifacts/data_transformation/${P}/train_features.pkl
      train_target_path: artifacts/data_transformation/${P}/train_target.pkl
      val_features_path: artifacts/data_transformation/${P}/val_features.pkl
      val_target_path: artifacts/data_transformation/${P}/val_target.pkl

# 4 in 1
model_trainer:
      # P
      train_feature_path: artifacts/data_transformation/${P}/train_features.pkl
      train_target_path: artifacts/data_transformation/${P}/train_target.pkl
      val_feature_path: artifacts/data_transformation/${P}/val_features.pkl
      val_target_path: artifacts/data_transformation/${P}/val_target.pkl

      # T Lưu các model và kết quả
      root_dir: artifacts/model_trainer/${T}
      best_model_path: artifacts/model_trainer/${T}/best_model.pkl
      list_monitor_components_path: artifacts/list_monitor_components.pkl

# MODEL_EVALUATION
model_evaluation:
      test_data_path: artifacts/data_correction_1/test_data.pkl

      preprocessor_path: artifacts/data_transformation/${PE}/preprocessor.pkl

      model_path: artifacts/model_trainer/${E}/best_model.pkl
      result: artifacts/test_model_results.txt
