stages:
      data_transformation:
            cmd: python src/classifier/pipeline/stage_03_data_transformation.py
            params:
                  - data_transformation

            outs:
                  - artifacts/data_transformation/${P}

      model_trainer:
            cmd: python src/classifier/pipeline/stage_04_model_training.py
            deps:
                  - artifacts/data_transformation/${P}
            params:
                  - model_name

      # MODEL_EVALUATION
      model_evaluation:
            cmd: python src/classifier/pipeline/stage_05_model_evaluation.py
            params:
                  - evaluated_data_transformation
                  - evaluated_model_name
